const actionTypes = {
    GET_POSTS_AJAX_START: 'GET_POSTS_AJAX_START',
    GET_POSTS_AJAX_SUCCESS: 'GET_POSTS_AJAX_SUCCESS',
    GET_POSTS_AJAX_FAILURE: 'GET_POSTS_AJAX_FAILURE',
    GET_POSTS: 'GET_POSTS',

    GET_TRENDING_AJAX_START: 'GET_TRENDING_AJAX_START',
    GET_TRENDING_AJAX_SUCCESS: 'GET_TRENDING_AJAX_SUCCESS',
    GET_TRENDING_AJAX_FAILURE: 'GET_TRENDING_AJAX_FAILURE',
    GET_TRENDING: 'GET_TRENDING',
};

export default actionTypes;